In [1]:
import pandas as pd

In [2]:
seoul_district = pd.read_csv("C:/Users/ITSC/Desktop/MiniPrj2/Git/Data/seoul_district.csv")

In [3]:
road_df = pd.read_csv("C:/Users/ITSC/Desktop/MiniPrj2/Git/Data/도로+현황_20240317153112.csv", skiprows = 4)

In [5]:
road_df = road_df.iloc[1:, 1:4]

In [6]:
road_df

   자치구별(2)      연장       면적
1      종로구  275701  2701070
2       중구  114232  1876189
3      용산구  281073  3154983
4      성동구  408339  3024659
5      광진구  324662  3436834
6     동대문구  327668  3151074
7      중랑구  331468  2861614
8      성북구  632634  4225186
9      강북구  227586  1984564
10     도봉구  257765  2354393
11     노원구  292679  3703776
12     은평구  359095  3518076
13    서대문구  311206  2744932
14     마포구  422128  4113591
15     양천구  411736  3700304
16     강서구  408521  4971891
17     구로구  296921  3227759
18     금천구  190888  2263876
19    영등포구  397092  4574217
20     동작구  250185  2754623
21     관악구  322203  3028487
22     서초구  391290  5564352
23     강남구  441986  5803381
24     송파구  365504  4784694
25     강동구  285839  3378733

In [8]:
road_df2 = road_df.sort_values(by = "자치구별(2)").loc[road_df["자치구별(2)"].isin(seoul_district["자치구"])].reset_index(drop = True)

In [9]:
road_df2 = road_df2.rename(columns = {"자치구별(2)" : "자치구"})

In [10]:
road_df2 = road_df2.iloc[:, :2]

In [11]:
road_df2

     자치구      연장
0    강남구  441986
1    강동구  285839
2    강북구  227586
3    강서구  408521
4    관악구  322203
5    광진구  324662
6    구로구  296921
7    금천구  190888
8    노원구  292679
9   동대문구  327668
10   동작구  250185
11   마포구  422128
12  서대문구  311206
13   서초구  391290
14   성동구  408339
15   송파구  365504
16   양천구  411736
17  영등포구  397092
18   용산구  281073
19   은평구  359095
20   종로구  275701
21    중구  114232
22   중랑구  331468

In [12]:
df_combined = pd.merge(seoul_district, road_df2, on = "자치구", how = "inner")

In [13]:
df_combined = df_combined.iloc[:, 1:]

In [14]:
df_combined["연장/면적"] = round(df_combined["연장"] / df_combined["면적 (km²)"], 2)

In [40]:
df_combined.iloc[:, 1:].corr()

,중대형 지하1층,중대형 1층,중대형 2층,중대형 3층,중대형 4층,중대형 5층,중대형 6-10층,소형 지하1층,소형 1층,소형 2층,면적 (km²),연장,연장/면적
중대형 지하1층,1.000000,0.770546,0.876414,0.850000,0.823290,0.810918,0.388460,0.421025,0.753174,0.765344,0.013904,-0.005846,-0.132792
중대형 1층,0.770546,1.000000,0.931897,0.838745,0.778494,0.696813,0.286921,0.223938,0.864503,0.706535,-0.248623,-0.385425,-0.129034
중대형 2층,0.876414,0.931897,1.000000,0.960617,0.918088,0.825178,0.436564,0.337744,0.879563,0.822097,-0.088571,-0.244442,-0.201250
중대형 3층,0.850000,0.838745,0.960617,1.000000,0.967779,0.892939,0.542065,0.377107,0.829402,0.771413,0.040345,-0.155092,-0.241733
중대형 4층,0.823290,0.778494,0.918088,0.967779,1.000000,0.878341,0.478581,0.496221,0.780073,0.791325,0.032800,-0.095111,-0.174570
중대형 5층,0.810918,0.696813,0.825178,0.892939,0.878341,1.000000,0.640052,0.423816,0.721824,0.630627,0.136045,0.018084,-0.181806
중대형 6-10층,0.388460,0.286921,0.436564,0.542065,0.478581,0.640052,1.000000,0.241695,0.337582,0.240153,0.226724,0.239657,-0.088775
소형 지하1층,0.421025,0.223938,0.337744,0.377107,0.496221,0.423816,0.241695,1.000000,0.143317,0.305666,0.073887,0.340854,0.183544
소형 1층,0.753174,0.864503,0.879563,0.829402,0.780073,0.721824,0.337582,0.143317,1.000000,0.859086,-0.184510,-0.269998,-0.113088
소형 2층,0.765344,0.706535,0.822097,0.771413,0.791325,0.630627,0.240153,0.305666,0.859086,1.000000,-0.041434,-0.068650,-0.122424
면적 (km²),0.013904,-0.248623,-0.088571,0.040345,0.032800,0.136045,0.226724,0.073887,-0.184510,-0.041434,1.000000,0.531860,-0.649072
연장,-0.005846,-0.385425,-0.244442,-0.155092,-0.095111,0.018084,0.239657,0.340854,-0.269998,-0.068650,0.531860,1.000000,0.258670
연장/면적,-0.132792,-0.129034,-0.201250,-0.241733,-0.174570,-0.181806,-0.088775,0.183544,-0.113088,-0.122424,-0.649072,0.258670,1.000000

In [19]:
df_combined.iloc[:, [2, 9, 13]].corr()

          중대형 1층     소형 1층     연장/면적
중대형 1층  1.000000  0.864503 -0.129034
소형 1층   0.864503  1.000000 -0.113088
연장/면적  -0.129034 -0.113088  1.000000